SELECT (NEXT VALUE FOR DBO.CUSTOMER_SEQUENCE) AS ID

SELECT cast(current_value as int) AS ID FROM sys.sequences WHERE name = 'CUSTOMER_SEQUENCE' ;

INSERT	INTO MSTCUSTOMER(CUSTOMER_NAME, SEX, BIRTHDAY, EMAIL, ADDRESS, INSERT_PSN_CD, UPDATE_PSN_CD, UPDATE_YMD)
VALUES ('Naruto', '0', '1997/10/25' ,'naruto97@gmail.com', 'Japanese', '1', '1', CURRENT_TIMESTAMP)
